export const PERSONAL_INFORMATION = "PERSONAL_INFORMATION"
export const PERSONAL_INFORMATION_SUCCESS = "PERSONAL_INFORMATION_SUCCESS"
export const PERSONAL_INFORMATION_FAIL = "PERSONAL_INFORMATION_FAIL"

export const EDUCATION = "EDUCATION"
export const EDUCATION_SUCCESS = "EDUCATION_SUCCESS"
export const EDUCATION_FAIL = "EDUCATION_FAIL"

export const EXPERIENCE = "EXPERIENCE"
export const EXPERIENCE_SUCCESS = "EXPERIENCE_SUCCESS"
export const EXPERIENCE_FAIL = "EXPERIENCE_FAIL"

export const PROJECTS = "PROJECTS"
export const PROJECTS_SUCCESS = "PROJECTS_SUCCESS"
export const PROJECTS_FAIL = "PROJECTS_FAIL"

export const SKILLS = "SKILLS"
export const SKILLS_SUCCESS = "SKILLS_SUCCESS"
export const SKILLS_FAIL = "SKILLS_FAIL"

export const ACHIEVEMENTS = "ACHIEVEMENTS"
export const ACHIEVEMENTS_SUCCESS = "ACHIEVEMENTS_SUCCESS"
export const ACHIEVEMENTS_FAIL = "ACHIEVEMENTS_FAIL"